/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: cameralib.i

package cameralib

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef long long swig_type_7;
typedef _gostring_ swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef _gostring_ swig_type_11;
typedef long long swig_type_12;
typedef _gostring_ swig_type_13;
extern void _wrap_Swig_free_cameralib_23f4c61520276210(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_cameralib_23f4c61520276210(swig_intgo arg1);
extern uintptr_t _wrap_new_Uint8Vector__SWIG_0_cameralib_23f4c61520276210(void);
extern uintptr_t _wrap_new_Uint8Vector__SWIG_1_cameralib_23f4c61520276210(swig_type_1 arg1);
extern uintptr_t _wrap_new_Uint8Vector__SWIG_2_cameralib_23f4c61520276210(uintptr_t arg1);
extern swig_type_2 _wrap_Uint8Vector_size_cameralib_23f4c61520276210(uintptr_t arg1);
extern swig_type_3 _wrap_Uint8Vector_capacity_cameralib_23f4c61520276210(uintptr_t arg1);
extern void _wrap_Uint8Vector_reserve_cameralib_23f4c61520276210(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_Uint8Vector_isEmpty_cameralib_23f4c61520276210(uintptr_t arg1);
extern void _wrap_Uint8Vector_clear_cameralib_23f4c61520276210(uintptr_t arg1);
extern void _wrap_Uint8Vector_add_cameralib_23f4c61520276210(uintptr_t arg1, char arg2);
extern char _wrap_Uint8Vector_get_cameralib_23f4c61520276210(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_Uint8Vector_set_cameralib_23f4c61520276210(uintptr_t arg1, swig_intgo arg2, char arg3);
extern void _wrap_delete_Uint8Vector_cameralib_23f4c61520276210(uintptr_t arg1);
extern void _wrap_vector_DeviceConfig_set_cameralib_23f4c61520276210(uintptr_t arg1);
extern uintptr_t _wrap_vector_DeviceConfig_get_cameralib_23f4c61520276210(void);
extern swig_type_5 _wrap_FormatCurrDatetime_cameralib_23f4c61520276210(void);
extern void _wrap_SaveFile__SWIG_0_cameralib_23f4c61520276210(uintptr_t arg1, swig_intgo arg2, swig_type_6 arg3);
extern void _wrap_SaveFile__SWIG_1_cameralib_23f4c61520276210(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_DisconnectedCallback_cameralib_23f4c61520276210(swig_type_7 arg1, swig_type_8 arg2, swig_type_9 arg3, uintptr_t arg4);
extern _Bool _wrap_MessCallBack_cameralib_23f4c61520276210(swig_type_10 arg1, swig_type_11 arg2, swig_type_12 arg3, uintptr_t arg4, uintptr_t arg5);
extern swig_intgo _wrap_Open_cameralib_23f4c61520276210(void);
extern swig_intgo _wrap_GetDeviceInfo_cameralib_23f4c61520276210(void);
extern swig_type_13 _wrap_FormatDeviceInfo_cameralib_23f4c61520276210(uintptr_t arg1);
#undef intgo
//#cgo LDFLAGS: -L/usr/local/lib -ljsoncpp -lprotobuf -luv -lNetSdk
#cgo LDFLAGS: -L/home/lining/GolandProjects/NXProductionTest/cameralib -ljsoncpp -lprotobuf -luv -lNetSdk
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

type swig_gostring struct {
	p uintptr
	n int
}

func swigCopyString(s string) string {
	p := *(*swig_gostring)(unsafe.Pointer(&s))
	r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
	Swig_free(p.p)
	return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_cameralib_23f4c61520276210(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrUint8Vector uintptr

func (p SwigcptrUint8Vector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrUint8Vector) SwigIsUint8Vector() {
}

func NewUint8Vector__SWIG_0() (_swig_ret Uint8Vector) {
	var swig_r Uint8Vector
	swig_r = (Uint8Vector)(SwigcptrUint8Vector(C._wrap_new_Uint8Vector__SWIG_0_cameralib_23f4c61520276210()))
	return swig_r
}

func NewUint8Vector__SWIG_1(arg1 int64) (_swig_ret Uint8Vector) {
	var swig_r Uint8Vector
	_swig_i_0 := arg1
	swig_r = (Uint8Vector)(SwigcptrUint8Vector(C._wrap_new_Uint8Vector__SWIG_1_cameralib_23f4c61520276210(C.swig_type_1(_swig_i_0))))
	return swig_r
}

func NewUint8Vector__SWIG_2(arg1 Uint8Vector) (_swig_ret Uint8Vector) {
	var swig_r Uint8Vector
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Uint8Vector)(SwigcptrUint8Vector(C._wrap_new_Uint8Vector__SWIG_2_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewUint8Vector(a ...interface{}) Uint8Vector {
	argc := len(a)
	if argc == 0 {
		return NewUint8Vector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewUint8Vector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewUint8Vector__SWIG_2(a[0].(Uint8Vector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrUint8Vector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Uint8Vector_size_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrUint8Vector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Uint8Vector_capacity_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrUint8Vector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Uint8Vector_reserve_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrUint8Vector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Uint8Vector_isEmpty_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrUint8Vector) Clear() {
	_swig_i_0 := arg1
	C._wrap_Uint8Vector_clear_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrUint8Vector) Add(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Uint8Vector_add_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrUint8Vector) Get(arg2 int) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (byte)(C._wrap_Uint8Vector_get_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrUint8Vector) Set(arg2 int, arg3 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Uint8Vector_set_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.char(_swig_i_2))
}

func DeleteUint8Vector(arg1 Uint8Vector) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Uint8Vector_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0))
}

type Uint8Vector interface {
	Swigcptr() uintptr
	SwigIsUint8Vector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 byte)
	Get(arg2 int) (_swig_ret byte)
	Set(arg2 int, arg3 byte)
}

func SetVector_DeviceConfig(arg1 Std_vector_Sl_sSearchDeviceConfig_Sg_) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_vector_DeviceConfig_set_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0))
}

func GetVector_DeviceConfig() (_swig_ret Std_vector_Sl_sSearchDeviceConfig_Sg_) {
	var swig_r Std_vector_Sl_sSearchDeviceConfig_Sg_
	swig_r = (Std_vector_Sl_sSearchDeviceConfig_Sg_)(SwigcptrStd_vector_Sl_sSearchDeviceConfig_Sg_(C._wrap_vector_DeviceConfig_get_cameralib_23f4c61520276210()))
	return swig_r
}

func FormatCurrDatetime() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_FormatCurrDatetime_cameralib_23f4c61520276210()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func SaveFile__SWIG_0(arg1 uintptr, arg2 int, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_SaveFile__SWIG_0_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func SaveFile__SWIG_1(arg1 uintptr, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SaveFile__SWIG_1_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func SaveFile(a ...interface{}) {
	argc := len(a)
	if argc == 2 {
		SaveFile__SWIG_1(a[0].(uintptr), a[1].(int))
		return
	}
	if argc == 3 {
		SaveFile__SWIG_0(a[0].(uintptr), a[1].(int), a[2].(string))
		return
	}
	panic("No match for overloaded function call")
}

func DisconnectedCallback(arg1 int64, arg2 string, arg3 int64, arg4 Puint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_DisconnectedCallback_cameralib_23f4c61520276210(C.swig_type_7(_swig_i_0), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_1)), C.swig_type_9(_swig_i_2), C.uintptr_t(_swig_i_3))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func MessCallBack(arg1 int64, arg2 string, arg3 uint64, arg4 Puint, arg5 EAlarmType) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5.Swigcptr()
	swig_r = (bool)(C._wrap_MessCallBack_cameralib_23f4c61520276210(C.swig_type_10(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1)), C.swig_type_12(_swig_i_2), C.uintptr_t(_swig_i_3), C.uintptr_t(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Open() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_Open_cameralib_23f4c61520276210())
	return swig_r
}

func GetDeviceInfo() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GetDeviceInfo_cameralib_23f4c61520276210())
	return swig_r
}

func FormatDeviceInfo(arg1 Std_vector_Sl_sSearchDeviceConfig_Sg_) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_FormatDeviceInfo_cameralib_23f4c61520276210(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

type SwigcptrStd_vector_Sl_sSearchDeviceConfig_Sg_ uintptr
type Std_vector_Sl_sSearchDeviceConfig_Sg_ interface {
	Swigcptr() uintptr
}

func (p SwigcptrStd_vector_Sl_sSearchDeviceConfig_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrPuint uintptr
type Puint interface {
	Swigcptr() uintptr
}

func (p SwigcptrPuint) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrEAlarmType uintptr
type EAlarmType interface {
	Swigcptr() uintptr
}

func (p SwigcptrEAlarmType) Swigcptr() uintptr {
	return uintptr(p)
}
